Update seek.js
SudhanPlayz/Discord-MusicBot pull request #1147
Opened 2022-12-28 11:38 UTC by Assassin654

**Please describe the changes this PR makes and why it should be merged:**
better ease of use for the seek command. allows users to put in something like 3h 30m instead of having to use 210m

**Status and versioning classification:**
Code changes have been tested against the Discord API, or there are no code changes
 know how to update typings and have done so, or typings don't need updating

2022-12-28 11:52 UTC, LewdHuTao approved these changes

2022-12-28 14:38 UTC, DevAmiyo commented on commands/slash/seek.js
> +							`Cannot seek current playing track. This may happened because seek duration has exceeded track duration or a incorrect time format`,
*an* incorrect time format

2022-12-28 14:56 UTC, DarrenOfficial requested changes

2022-12-28 14:56 UTC, DarrenOfficial commented on commands/slash/seek.js
> +							`Cannot seek current playing track. This may happened because seek duration has exceeded track duration or a incorrect time format`,
`Unable to seek current playing track. This may be due to exceeding track duration or incorrect time format. Please check and try again`

2023-01-06 19:06 UTC, DevAmiyo approved these changes

2023-02-24 17:11 UTC, DarrenOfficial approved these changes

2023-02-24 17:11 UTC, merged