Vote skip if >= 3
SudhanPlayz/Discord-MusicBot pull request #1191
Opened 2023-03-05 23:56 UTC by clownidze1337

**Please describe the changes this PR makes and why it should be merged:**

- Added vote skip function when there is equal or more than 3 people in voice channel

2023-03-06 09:30 UTC, Assassin654 commented
make this toggleable.

2023-04-03 01:03 UTC, clownidze1337 commented
@Assassin654 
Done. Sorry for that delay 😮‍💨 
Was kinda busy...

2023-04-03 12:19 UTC, DarrenOfficial commented
> make this toggleable.

why so rude

2023-04-03 12:21 UTC, DarrenOfficial requested changes

2023-04-03 12:21 UTC, DarrenOfficial commented on commands/togglevote.js
> +};
I think this is quite a rough way to add vote skip toggle feature. It's better if the way to toggle on & off is permission based.

2023-04-03 13:23 UTC, clownidze1337 commented
I could do it using admins ids from config file, but i decided that people may not want edit file often, so i did it with Discord Administrator permission.

2023-04-05 15:12 UTC, clownidze1337 commented
@DarrenOfficial

2023-04-05 15:15 UTC, closed without merging