Ability to increast the retryamount for lavalink
SudhanPlayz/Discord-MusicBot pull request #371
Opened 2021-09-03 17:30 UTC by DarrenOfficial

**Please describe the changes this PR makes and why it should be merged:**
This pr add a way so that if the lavalink restart it auto reconnects and add upto unlimited reconnect retry amount.

**Status and versioning classification:**

2021-09-04 02:17 UTC, joeyk710 commented
Looks good to me

2021-09-06 11:41 UTC, SudhanPlayz approved these changes

2021-09-09 04:14 UTC, SudhanPlayz commented on botconfig.js
> +    retrydelay: 15000, // Delay for reconnect in ms.
```suggestion
    retryDelay: 15000, // Delay for reconnect in ms.
```

2021-09-09 04:14 UTC, SudhanPlayz commented on structures/DiscordMusicBot.js
> +          retryDelay: this.botconfig.Lavalink.retrydelay,
```suggestion
          retryDelay: this.botconfig.Lavalink.retryDelay,
```

2021-09-09 04:14 UTC, SudhanPlayz commented on structures/DiscordMusicBot.js
> +          retryAmount: this.botconfig.Lavalink.retryamount,
```suggestion
          retryAmount: this.botconfig.Lavalink.retryAmount,
```

2021-09-09 04:15 UTC, SudhanPlayz commented on botconfig.js
> +    retryamount: 10000000, // Retry amout if the lavalink is dead and/or restarting.
```suggestion
    retryAmount: 10000000, // Retry amout if the lavalink is dead and/or restarting.
```

2021-09-09 04:16 UTC, SudhanPlayz requested changes
Change

2021-09-09 09:41 UTC, DarrenOfficial commented
Fixed 👍🏼

2021-09-09 14:56 UTC, SudhanPlayz approved these changes

2021-09-19 05:32 UTC, SudhanPlayz commented
Fix confilcts

2021-09-19 21:10 UTC, DarrenOfficial commented
fixed.

2021-09-19 21:17 UTC, closed without merging