Added bump command
SudhanPlayz/Discord-MusicBot pull request #422
Opened 2021-09-25 06:23 UTC by poppin-fresh

**Please describe the changes this PR makes and why it should be merged:**

Moves the selected queued track to the front of the queue
e.g. (>bump 12) Will move song from position 12 to 1

**Status and versioning classification:**

2021-09-25 11:11 UTC, Kakarot-0690 commented
have you tested this properly?

2021-09-25 14:26 UTC, poppin-fresh commented
> have you tested this properly?

Yes.

2021-09-26 06:55 UTC, Kakarot-0690 commented
> > have you tested this properly?
> 
> Yes, extensively. There shouldn't be any problems, however if you find something please let me know.

yup looks pretty good to me

2021-09-26 14:58 UTC, DarrenOfficial commented on commands/bump.js
> +		client.sendTime(message.channel, "✅ | **" + track.title + "** has been moved to the front of the queue.");
/root/sudhan/poppin-fresh/commands/bump.js:34
                client.sendTime(message.channel, "✅ | **" + track.title + "** has been moved to the front of the queue.");
                                                                  ^
TypeError: Cannot read property 'title' of undefined
    at Object.run (/root/sudhan/poppin-fresh/commands/bump.js:34:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

2021-09-26 15:00 UTC, DarrenOfficial requested changes
Running Bump without number crashed the bot, please re-check
```bash
/root/sudhan/poppin-fresh/commands/bump.js:34
                client.sendTime(message.channel, "✅ | **" + track.title + "** has been moved to the front of the queue.");
                                                                  ^

TypeError: Cannot read property 'title' of undefined
    at Object.run (/root/sudhan/poppin-fresh/commands/bump.js:34:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

2021-09-26 15:29 UTC, poppin-fresh commented
@DarrenOfficial fixed in cc04f2f.
Had this in my version but pushed an older one, my bad.

2021-09-28 12:40 UTC, Kakarot-0690 commented
> @DarrenOfficial fixed in [cc04f2f](https://github.com/SudhanPlayz/Discord-MusicBot/commit/cc04f2fcbd189a343522deefadc11efca2978839). Had this in my version but pushed an older one, my bad.

tested and tried, works

2021-09-29 06:08 UTC, merged