Improve messageCreate.js
SudhanPlayz/Discord-MusicBot pull request #981
Opened 2022-07-08 12:27 UTC by XstreamSpeed

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**
Node.js: v16.7.0 | discord.js: v13.8.0 | branch: v5

**Preview:**
![Screenshot_9](https://user-images.githubusercontent.com/79592017/177991854-44660d8f-1834-468e-8f81-5edec9c0ae86.png)

- Code changes have been tested against the Discord API, or there are no code changes

2022-07-08 15:28 UTC, DevAmiyo approved these changes

2022-07-09 12:09 UTC, DevAmiyo requested changes

2022-07-09 12:09 UTC, DevAmiyo commented on events/messageCreate.js
> +		.setURL(`https://discord.com/oauth2/authorize?client_id=${client.config.clientId}&permissions=${client.config.permissions}&scope=bot%20applications.commands`),
Use scopes from config
```js
.setURL(`https://discord.com/oauth2/authorize?client_id=${client.config.clientId}&permissions=${client.config.permissions}&scope=${client.config.scopes.toString().replace(/,/g, '%20')}`),
```

2022-07-09 13:32 UTC, DevAmiyo commented
I have made some changes
> - Use scopes from config
> - Keep hyperlink in re-invite
> - Add dashboard button shown in screenshot as its a nice feature to add

```js
const { MessageEmbed, MessageButton, MessageActionRow } = require("discord.js");

module.exports = async (client, message) => {
	const mention = new RegExp(`^<@!?${ client.user.id }>( |)$`);
	const invite = `https://discord.com/oauth2/authorize?client_id=${client.config.clientId}&permissions=${client.config.permissions}&scope=${client.config.scopes.toString().replace(/,/g, '%20')}`;
	const buttons = new MessageActionRow()
	.addComponents(
		new MessageButton()
			.setStyle("LINK")
			.setLabel('Invite me')
			.setURL(invite),
		new MessageButton()
			.setStyle("LINK")
			.setLabel('Support server')
			.setURL(client.config.supportServer),
		new MessageButton()
			.setStyle("LINK")
			.setLabel('Dashboard')
			.setURL(client.config.website),
	);

	if (message.content.match(mention)) {
		const mentionEmbed = new MessageEmbed()
		.setColor(client.config.embedColor)
		.setDescription(
			`My prefix on this server is \`/\` (Slash Command).\nTo get started you can type \`/help\` to see all my commands.\nIf you can't see it, Please [re-invite](invite) me with the correct permissions.`
		);

		message.channel.send({
			embeds: [mentionEmbed],
			components: [buttons],
		});
	}
};
```

2022-07-09 13:34 UTC, XstreamSpeed commented
> I have made some changes
> 
> > * Use scopes from config
> > * Keep hyperlink in re-invite
> > * Add dashboard button shown in screenshot as its a nice feature to add
> 
> ```js
> const { MessageEmbed, MessageButton, MessageActionRow } = require("discord.js");
> 
> module.exports = async (client, message) => {
> 	const mention = new RegExp(`^<@!?${ client.user.id }>( |)$`);
> 	const invite = `https://discord.com/oauth2/authorize?client_id=${client.config.clientId}&permissions=${client.config.permissions}&scope=${client.config.scopes.toString().replace(/,/g, '%20')}`;
> 	const buttons = new MessageActionRow()
> 	.addComponents(
> 		new MessageButton()
> 			.setStyle("LINK")
> 			.setLabel('Invite me')
> 			.setURL(invite),
> 		new MessageButton()
> 			.setStyle("LINK")
> 			.setLabel('Support server')
> 			.setURL(client.config.supportServer),
> 		new MessageButton()
> 			.setStyle("LINK")
> 			.setLabel('Dashboard')
> 			.setURL(client.config.website),
> 	);
> 
> 	if (message.content.match(mention)) {
> 		const mentionEmbed = new MessageEmbed()
> 		.setColor(client.config.embedColor)
> 		.setDescription(
> 			`My prefix on this server is \`/\` (Slash Command).\nTo get started you can type \`/help\` to see all my commands.\nIf you can't see it, Please [re-invite](invite) me with the correct permissions.`
> 		);
> 
> 		message.channel.send({
> 			embeds: [mentionEmbed],
> 			components: [buttons],
> 		});
> 	}
> };
> ```

I will use the scopes from the config, thank you for the suggestion, I don't know why you'd want a hyperlink instead of a nice button, we'll decide it later and for the dashboard, I kind of added a scope in my own bot for the dashboard if that seems fine I'll commit it in.

2022-07-09 15:25 UTC, DevAmiyo commented
> I will use the scopes from the config, thank you for the suggestion, I don't know why you'd want a hyperlink instead of a nice button, we'll decide it later and for the dashboard, I kind of added a scope in my own bot for the dashboard if that seems fine I'll commit it in, some people don't know how to get the link to show the dashboard so I'm a bit skeptical on that.

- I'm not asking to remove the button but the button says "Invite Me" but the sentence is "Please reinvite me with the correct permissions.". So, I just think that the button can stay and the reinvite text could also have a hyperlink because its asking the user to reinvite the bot into the same server. Idk if it makes sense, but yeah.
- I agree with you, but eventually when the dashboard is fully built, we can add a button to view the dashboard or maybe add a condition if the value of website in config is not empty or localhost only then it would show the button. We can decide on that later on.
- Otherwise, everything looks good to me.

2022-07-10 00:42 UTC, JotaroKujo0525 approved these changes

2022-07-10 05:37 UTC, XstreamSpeed commented
> > I will use the scopes from the config, thank you for the suggestion, I don't know why you'd want a hyperlink instead of a nice button, we'll decide it later and for the dashboard, I kind of added a scope in my own bot for the dashboard if that seems fine I'll commit it in, some people don't know how to get the link to show the dashboard so I'm a bit skeptical on that.
> 
> * I'm not asking to remove the button but the button says "Invite Me" but the sentence is "Please reinvite me with the correct permissions.". So, I just think that the button can stay and the reinvite text could also have a hyperlink because its asking the user to reinvite the bot into the same server. Idk if it makes sense, but yeah.
> * I agree with you, but eventually when the dashboard is fully built, we can add a button to view the dashboard or maybe add a condition if the value of website in config is not empty or localhost only then it would show the button. We can decide on that later on.
> * Otherwise, everything looks good to me.

Alright then!

2022-07-10 11:25 UTC, XstreamSpeed commented
Bro why does this happen every. single. time, i make a pr but that pr is the only one that is not merged :/

2022-07-10 11:36 UTC, DevAmiyo commented
> Bro why does this happen every. single. time, i make a pr but that pr is the only one that is not merged :/

lmao 😂

2022-07-10 12:48 UTC, XstreamSpeed commented
> > Bro why does this happen every. single. time, i make a pr but that pr is the only one that is not merged :/
> 
> lmao 😂

watch this pr get closed

2022-07-10 14:14 UTC, Saud-97 commented
> Bro why does this happen every. single. time, i make a pr but that pr is the only one that is not merged :/

Its not actively maintained probably they are busy. I got PRs from 18 days ago lol.

2022-07-10 14:15 UTC, Saud-97 commented
Btw did you try and kick the bot and then clicked the invite me button? Does it work when bot is not in the server?

2022-07-10 14:56 UTC, DevAmiyo commented
> Btw did you try and kick the bot and then clicked the invite me button? Does it work when bot is not in the server?

Yup, just checked. The button works regardless if the bot is in the server.

2022-07-13 08:58 UTC, XstreamSpeed commented
> > > Bro why does this happen every. single. time, i make a pr but that pr is the only one that is not merged :/
> > 
> > 
> > Its not actively maintained probably they are busy. I got PRs from 18 days ago lol.
> 
> yes, and also cause it needs testing before merging to master branch. although, at this point I don't test @XstreamSpeed PR anymore. I rather let Sudhan or someone else do it. as their commit (no offense) is _usually_ untested and previously broke multiple stuff. also the code formatting is a bit off. _this is probably due to @XstreamSpeed using github instead of their IDE to commit these changes._
> 
> ![IMG_2283](https://user-images.githubusercontent.com/55406094/178687552-1c58128c-f530-4585-88c9-72f4fdf91847.jpeg)

This is tested as the image is shows above

2022-07-13 10:54 UTC, Neko-Life commented
> I first write the code I IDE and then I publish it on github

By "publish" you mean "copy the codes from the IDE and paste it on my fork" am I right

2022-07-13 14:43 UTC, XstreamSpeed commented
> > I first write the code I IDE and then I publish it on github
> 
> By "publish" you mean "copy the codes from the IDE and paste it on my fork" am I right

Kind of, but I reformat the code in github since github messes up tabs and spaces

2022-07-13 19:33 UTC, DevAmiyo commented
> Kind of, but I reformat the code in github since github messes up tabs and spaces

Why don't you just use [Github Desktop](https://desktop.github.com) and push it directly to the fork?

2022-07-13 21:38 UTC, DarrenOfficial commented
Github desktop is bloated tbh, it's better to just use [Git cli](https://git-scm.com/)

2022-07-14 01:47 UTC, XstreamSpeed commented
> > Kind of, but I reformat the code in github since github messes up tabs and spaces
> 
> Why don't you just use [Github Desktop](https://desktop.github.com) and push it directly to the fork?

tbh I would use vscode and commit changes from there but i guess im too lazy

2022-07-17 13:18 UTC, XstreamSpeed commented
waiting for the day where darren or sudhan do something with this..

2022-08-01 02:22 UTC, JotaroKujo0525 commented
so er, do we merge this or nah

2022-08-03 11:27 UTC, XstreamSpeed commented
> so er, do we merge this or nah

i mean its tested and shit..

2022-08-07 11:07 UTC, SudhanPlayz approved these changes

2022-08-07 11:07 UTC, merged